GET http://localhost:3000/users/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIzLCJlbWFpbCI6ImZhdGltYTJAZ21haWwuY29tIiwiaWF0IjoxNzM3MTM0NjkzLCJleHAiOjE3MzcxMzgyOTMsImF1ZCI6ImxvY2FsaG9zdDozMDAwIiwiaXNzIjoibG9jYWxob3N0OjMwMDAifQ.dWPxRxDFhrA5pJT4ur3mCHNTmnN3X_EE-VTr-9zFyVs